# Import Travis configuration from dev-tools repo
version: ~> 1.0
import:
  - source: humanmade/altis-dev-tools:travis/module.yml@d762f58
    mode: deep_merge_append

# Add your custom config below, which will merge with the default module config from the section above.

script:
  - cd $HOME/test-root && composer dev-tools phpunit vendor/$ALTIS_PACKAGE
