sudo: false
dist: xenial

language: php

services:
  - docker

env:
  - COMPOSE_HTTP_TIMEOUT=360
  - ES_MEM_LIMIT=2g

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/docker-images

before_install:
  - docker load -i $HOME/docker-images/images.tar || true

before_cache:
  - docker save -o $HOME/docker-images/images.tar $(docker images -a -q)

matrix:
  include:
    - php: 7.2

before_script:
  - composer install
  - composer local-server start

script:
  - composer dev-tools phpunit
