<?php
/**
 * Tests Config file.
 *
 * This file is automatically generated, do not edit or delete this file.
 */

// Set tests table prefix.
$table_prefix = 'wptests_';

// Load custom tests config file.
if ( file_exists( __DIR__ . '/wp-tests-config.php' ) ) {
	require __DIR__ . '/wp-tests-config.php';
}

defined( 'WP_TESTS_DOMAIN' ) or define( 'WP_TESTS_DOMAIN', 'example.org' );
defined( 'WP_TESTS_EMAIL' ) or define( 'WP_TESTS_EMAIL', 'admin@example.org' );
defined( 'WP_TESTS_TITLE' ) or define( 'WP_TESTS_TITLE', 'Test Blog' );


//.Load Altis.
require_once dirname( __DIR__ ) . '/wp-config.php';
